<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>0.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="9.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Smooth.Shared.Razor\Smooth.Shared.Razor.csproj" />
      <ProjectReference Include="..\Smooth.Web.Application\Smooth.Web.Application.csproj" />
      <ProjectReference Include="..\Smooth.Web.Infrastructure\Smooth.Web.Infrastructure.csproj" />
    </ItemGroup>

</Project>
