name: Build and deploy ASP.Net Core app to Azure Web App - app-smooth-web-stage

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (without submodules)
        uses: actions/checkout@v2
        with:
          submodules: false  # We'll manually handle submodule placement later

      - name: Clone Smooth.Shared submodule in the correct location
        run: |
          git clone https://github.com/Ekzakt/Smooth.Shared ../Smooth.Shared

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Restore dependencies, including for submodule
        working-directory: ${{ github.workspace }}/src/Smooth.Web
        run: dotnet restore

      - name: Update Build Number and Pack Projects
        run: |
          offset=48
          runNumber=51
          versionNumber=$((runNumber - offset))
          projects=(
            "/home/runner/work/Smooth.Web/Smooth.Web/src/Smooth.Web/Smooth.Web.csproj"
          )
          for project in "${projects[@]}"; do
            sed -i "s/\(<Version>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1$versionNumber/" "$project"
          done

      - name: Build Smooth.Web project
        working-directory: ${{ github.workspace }}/src/Smooth.Web
        run: dotnet build --configuration Release

      - name: Log the run number
        run: echo "This is run number ${{ github.run_number }} of this workflow"

      - name: Publish Smooth.Web project
        working-directory: ${{ github.workspace }}/src/Smooth.Web
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-smooth-web-stage'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B4965181552C4F59BCE5376DAEF51BC0 }}
          package: .
