name: Build and deploy ASP.Net Core app to Azure Web App - app-smooth-web-stage

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (including submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Ensures all submodules are fetched

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: List files in workspace
        run: ls -R ${{ github.workspace }}

      - name: Build with dotnet
        working-directory: ./Smooth.Sensation/src/Smooth.Web
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        working-directory: ./Smooth.Sensation/src/Smooth.Web
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-smooth-web-stage'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B4965181552C4F59BCE5376DAEF51BC0 }}
          package: .
