name: Build and deploy ASP.Net Core app to Azure Web App - app-smooth-web-stage

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check working directory
        run: pwd

      - name: List files in workspace
        run: ls -R ${{ github.workspace }}
  
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true
  
      # - name: Build with dotnet
      #   run: dotnet build --configuration Release

      - name: Restore dependencies
        run: dotnet restore Smooth.Web/Smooth.Web/Smooth.Web.csproj

      - name: Build the solution
        run: dotnet build Smooth.Web/Smooth.Web/Smooth.Web.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-smooth-web-stage'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B4965181552C4F59BCE5376DAEF51BC0 }}
          package: .
